import type { Metadata } from "next";
import BodyWrapper from "../components/BodyWrapper";
import "./globals.css";
import Theme from "./context/ThemeProvider";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <Theme>
    <html lang="en">
      <BodyWrapper>
       {children}
      </BodyWrapper>
    </html>
    </Theme>
  );
}
